export type SourceType =
  | "Internal Aman Data" | "Official Company Sources" | "Government Sources" | "Regulatory Sources"
  | "Financial Reports" | "Credible Research" | "Industry Reports" | "News" | "Competitor Websites";

export interface Source {
  id: string; name: string; url: string; date: string; claim: string; type: SourceType;
  confidence: "High" | "Medium" | "Low"; note?: string;
}

// Retrieved by live web research on 2026-09-20. AI-generated text is never listed as a source.
export const SOURCES: Source[] = [
  { id: "S1", name: "Financial Regulatory Authority (FRA) - gold investment fund certificates vs direct gold trading", url: "https://fra.gov.eg/en/fra_news/%D8%A7%D9%84%D8%B1%D9%82%D8%A7%D8%A8%D8%A9-%D8%A7%D9%84%D9%85%D8%A7%D9%84%D9%8A%D8%A9-%D8%AA%D8%A4%D9%83%D8%AF-%D8%A3%D9%86%D9%87%D8%A7-%D8%AA%D9%86%D8%B8%D9%85-%D8%A7%D9%84%D8%A7%D8%B3%D8%AA%D8%AB/", date: "2025-05-06", claim: "FRA regulates gold investment fund certificates, not direct gold trading with the public (governed by the Commercial Law 1999 and Precious Metals & Gemstones Law 1976). Three FRA-approved gold funds held ~EGP 2.1bn from ~200k investors.", type: "Regulatory Sources", confidence: "High" },
  { id: "S2", name: "Arab Finance - Thndr launches digital gold investment service", url: "https://www.arabfinance.com/en/news/newdetails/thndr-launches-digital-gold-investment-service", date: "2026-06-24 (as reported)", claim: "Thndr Gold: 0.001 g minimum, flat 1% fee on buy and sell, custody at EGYCASH, execution three times per working day (Sun-Thu).", type: "News", confidence: "Medium" },
  { id: "S3", name: "mngm - homepage", url: "https://mngm.com/", date: "2026-09-20 (accessed)", claim: "Fractional 24k gold in multiples of 0.1 g; bid/ask at international benchmark; CBE-licensed insured vault; physical delivery; partners incl. Evolve Holding, NBE, Fawry, PayTabs, EgyCash.", type: "Competitor Websites", confidence: "Medium", note: "Self-reported by provider; fees/spread not published on the page reviewed." },
  { id: "S4", name: "Goldady - homepage", url: "https://goldady.com/en", date: "2026-09-20 (accessed)", claim: "From 1 g; claims up to 70% lower making charges vs traditional retailers; EgyCash custody; home delivery; lists Egyptian commercial/hallmark/IT licences.", type: "Competitor Websites", confidence: "Low", note: "Marketing claim, unverified." },
  { id: "S5", name: "Sada Elbalad - Egyptians' gold purchases fall 10% in 2025 (citing World Gold Council)", url: "https://see.news/egyptians-gold-purchases-fall-10-in-2025-as-bar-demand-jumps-in-q4", date: "2026 (2025 full-year data)", claim: "Egypt gold demand 45.1 t in 2025 (-10%); jewelry 21.5 t (-18%); bars & coins 23.6 t (-2%); Q4 2025 12.6 t.", type: "News", confidence: "Medium", note: "Secondary report. Verify against World Gold Council Gold Demand Trends before citing to management." },
  { id: "S6", name: "World Gold Council - Gold Demand Trends: Q4 and Full Year 2025", url: "https://www.gold.org/goldhub/research/gold-demand-trends/gold-demand-trends-full-year-2025", date: "2026", claim: "Primary source for global/country gold demand (page located; Egypt-specific figures not extracted directly).", type: "Industry Reports", confidence: "Medium" },
  { id: "S7", name: "First Page Sage - Fintech CAC Benchmarks", url: "https://firstpagesage.com/seo-blog/fintech-cac-benchmarks-report/", date: "2025-12-23 (last modified)", claim: "Consumer 'Investing & Trading' fintech CAC: USD 166 (consumer overall USD 202).", type: "Industry Reports", confidence: "Low", note: "US-based consultancy, client-base data, geography unstated. Paid new-customer CAC; overstates cross-sell CAC to existing app users." },
  { id: "S8", name: "Wise - USD to EGP exchange rate history", url: "https://wise.com/us/currency-converter/usd-to-egp-rate/history", date: "2026-09-14 to 2026-09-16", claim: "USD/EGP traded 51.35-52.24 during 14-16 Sep 2026.", type: "Financial Reports", confidence: "Medium" },
  { id: "S9", name: "The New Arab - Egypt launches first-ever gold investment fund", url: "https://www.newarab.com/news/egypt-launches-first-ever-gold-investment-fund", date: "not verified", claim: "First gold fund managed by Evolve Azimut (JV of Evolve Holding and Azimut Egypt).", type: "News", confidence: "Low", note: "Found in search results, page not opened." },
  { id: "S10", name: "mngm - Egypt's precious metals ecosystem", url: "https://mngm.com/learn/egypts-precious-metals-ecosystem-a-game-changer-for-egypts-financial-inclusion", date: "undated", claim: "Context on financial inclusion and digital precious metals; 67% unbanked share and 57.3% internet penetration (2021 figures, dated).", type: "Competitor Websites", confidence: "Low", note: "Provider marketing content; figures are dated." },
  { id: "S11", name: "Mordor Intelligence - MENA Fintech Market", url: "https://www.mordorintelligence.com/industry-reports/mena-fintech-market", date: "not verified", claim: "Search-result summary: <3% of MENA population actively invests in financial assets; cash >80% of Egyptian retail spending.", type: "Industry Reports", confidence: "Low", note: "Search snippet only; not verified against the report." },
];
